package testnet

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/hive/hivesim"
	"github.com/ethereum/hive/taiko/params"
	beacon_client "github.com/marioevz/eth-clients/clients/beacon"
	exec_client "github.com/marioevz/eth-clients/clients/execution"
	"github.com/protolambda/zrnt/eth2/beacon/common"
	"math/big"
	"strings"
	"taiko2/common/clients"
	cl "taiko2/common/config/consensus"
	consensus_config "taiko2/common/config/consensus"
	el "taiko2/common/config/execution"
	"taiko2/common/utils"
)

var (
	DEFAULT_SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY = big.NewInt(128)
	DEFAULT_MAX_CONSECUTIVE_ERRORS_ON_WAITS     = 3
)

// PreparedTestnet has all the options for starting nodes, ready to build the network.
type PreparedTestnet struct {
	// Consensus chain configuration
	Spec *consensus_config.Spec

	// Execution chain configuration and genesis info
	ExecutionGenesis *el.ExecutionGenesis

	// L1chain configuration to apply to every node of the given type
	executionOpts hivesim.StartOption
	validatorOpts hivesim.StartOption
	beaconOpts    hivesim.StartOption

	// L2chain configuration to apply to every node of the given type
	taikoGethOpts hivesim.StartOption
	driverOpts    hivesim.StartOption
	proposerOpts  hivesim.StartOption
	proverOpts    hivesim.StartOption
}

func getLogLevelString(logLevel int) string {
	switch logLevel {
	case 0:
		return "silent"
	case 1:
		return "error"
	case 2:
		return "warn"
	case 3:
		return "info"
	case 4:
		return "debug"
	case 5:
		return "detail"
	}
	return "info"
}

// Build all artifacts require to start a testnet.
func PrepareTestnet(
	cfg *Config,
	generateState *el.GenesisState,
) (*PreparedTestnet, error) {
	// Show cfg file
	if configJson, err := json.MarshalIndent(cfg, "", "  "); err != nil {
		panic(err)
	} else {
		fmt.Printf("Testnet config: %s\n", configJson)
	}

	executionGenesis, spec, err := el.BuildExecutionGenesis(generateState)
	if err != nil {
		return nil, fmt.Errorf("error producing execution genesis: %v", err)
	}

	genesisJsonBundle, err := el.ExecutionBundle(executionGenesis.Genesis)
	if err != nil {
		return nil, fmt.Errorf("unable to bundle execution genesis: %v", err)
	}

	// Write info so that the genesis state can be generated by the client
	genesisSSZBundle, err := cl.StateBundle(executionGenesis.GenesisState)
	if err != nil {
		return nil, fmt.Errorf("error producing state bundle: %v", err)
	}

	configBundle, err := cl.ConfigBundle(params.ConfigContent)
	if err != nil {
		return nil, fmt.Errorf("error producing consensus cfg bundle: %v", err)
	}

	commonParams := hivesim.Params{
		"HIVE_LOGLEVEL":           getLogLevelString(cfg.LogLevel),
		"HIVE_TAIKO2_JWT_SECRET":  cfg.JWTSecret,
		"HIVE_TAIKO2_FEE_RECEIPT": cfg.FeeReceipt,
	}

	executionOpts := hivesim.Bundle(
		genesisJsonBundle,
		hivesim.Params{
			"HIVE_TAIKO2_FEE_RECEIPT": cfg.FeeReceipt,
			"HIVE_TAIKO2_CHAIN_ID":    fmt.Sprintf("%d", executionGenesis.ChainID()),
		},
		commonParams,
	)

	// Pre-generate PoW chains for clients that require it
	for i := 0; i < len(cfg.NodeDefinitions); i++ {
		if cfg.NodeDefinitions[i].ChainGenerator != nil {
			cfg.NodeDefinitions[i].Chain, err = cfg.NodeDefinitions[i].ChainGenerator.Generate(
				executionGenesis,
			)
			if err != nil {
				return nil, fmt.Errorf("unable to generate PoW chains for node %d: %v", i, err)
			}
			fmt.Printf("Generated chain for node %d:\n", i+1)
			for j, b := range cfg.NodeDefinitions[i].Chain {
				js, _ := json.MarshalIndent(b.Header(), "", "  ")
				fmt.Printf("Block %d: %s\n", j, js)
			}
		}
	}

	beaconParams := hivesim.Params{
		"HIVE_TAIKO2_METRICS_PORT":                fmt.Sprintf("%d", beacon_client.PortMetrics),
		"HIVE_TAIKO2_DEPOSIT_CONTRACT_ADDRESS":    executionGenesis.DepositAddress,
		"HIVE_TAIKO2_DEPOSIT_DEPLOY_BLOCK_NUMBER": fmt.Sprintf("%d", executionGenesis.Block.NumberU64()),
		"HIVE_TAIKO2_ETH1_GENESIS_TIME":           fmt.Sprintf("%d", executionGenesis.Genesis.Timestamp),
		"HIVE_TAIKO2_CHAIN_ID":                    fmt.Sprintf("%d", executionGenesis.ChainID()),
		"HIVE_TAIKO2_MIN_SYNC_PEERS":              "0",
	}

	beaconOpts := hivesim.Bundle(
		configBundle,
		genesisSSZBundle,
		commonParams,
		beaconParams,
	)

	validatorParams := hivesim.Params{
		"HIVE_TAIKO2_NUM_VALIDATORS": fmt.Sprintf("%d", executionGenesis.GenesisState.NumValidators()),
	}

	validatorOpts := hivesim.Bundle(
		configBundle,
		commonParams,
		validatorParams,
	)

	taikoGethOpts := hivesim.Bundle(hivesim.Params{
		"HIVE_TAIKO2_JWT_SECRET":  cfg.JWTSecret,
		"HIVE_TAIKO2_FEE_RECEIPT": cfg.FeeReceipt,
		"HIVE_LOGLEVEL":           fmt.Sprintf("%d", cfg.LogLevel),
	})

	return &PreparedTestnet{
		Spec:             spec,
		ExecutionGenesis: executionGenesis,
		executionOpts:    executionOpts,
		beaconOpts:       beaconOpts,
		validatorOpts:    validatorOpts,

		taikoGethOpts: taikoGethOpts,
		driverOpts:    hivesim.Bundle(commonParams),
		proposerOpts:  hivesim.Bundle(commonParams),
		proverOpts:    hivesim.Bundle(commonParams),
	}, nil
}

func (p *PreparedTestnet) createTestnet(t *hivesim.T) *Testnet {
	genesisState := p.ExecutionGenesis.GenesisState
	genesisTime := genesisState.GenesisTime()
	genesisValidatorsRoot := genesisState.GenesisValidatorsRoot()
	return &Testnet{
		T:                     t,
		genesisTime:           common.Timestamp(genesisTime),
		genesisValidatorsRoot: common.Root(genesisValidatorsRoot),
		spec:                  p.Spec,
		executionGenesis:      p.ExecutionGenesis,

		Validators:      genesisState.Validators(),
		ValidatorGroups: make(map[string]*utils.Validators),
	}
}

// Prepares an execution client object with all the necessary information
// to start
func (p *PreparedTestnet) prepareExecutionNode(
	parentCtx context.Context,
	testnet *Testnet,
	eth1Def *hivesim.ClientDefinition,
	consensus el.ExecutionConsensus,
	chain []*types.Block,
	config clients.ExecutionClientConfig,
	deploy bool,
) *clients.ExecutionClient {
	if eth1Def == nil {
		return nil
	}
	testnet.Logf("Preparing execution node: %s (%s)", eth1Def.Name, eth1Def.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: eth1Def,
		Port:                 exec_client.PortEngineRPC,
	}

	// This method will return the options used to run the client.
	// Requires a method that returns the rest of the currently running
	// execution clients on the network at startup.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.executionOpts}
		opts = append(opts, consensus.HiveParams(config.ClientIndex))

		currentlyRunningEcs := testnet.ExecutionClients().
			Running().
			Subnet(config.Subnet)
		if len(currentlyRunningEcs) > 0 {
			bootnode, err := currentlyRunningEcs.Enodes()
			if err != nil {
				return nil, err
			}

			// Make the client connect to the first eth1 node, as a bootnode for the eth1 net
			opts = append(opts, hivesim.Params{"HIVE_BOOTNODE": bootnode})
		}
		opts = append(
			opts,
			hivesim.Params{
				"HIVE_TERMINAL_TOTAL_DIFFICULTY": fmt.Sprintf("%d", config.TerminalTotalDifficulty),
			},
		)
		genesis := testnet.ExecutionGenesis().ToBlock()
		if config.TerminalTotalDifficulty <= genesis.Difficulty().Int64() {
			opts = append(
				opts,
				hivesim.Params{
					"HIVE_TERMINAL_BLOCK_HASH":   fmt.Sprintf("%s", genesis.Hash()),
					"HIVE_TERMINAL_BLOCK_NUMBER": fmt.Sprintf("%d", genesis.NumberU64()),
				},
			)
		}

		if len(chain) > 0 {
			// Bundle the chain into the container
			chainParam, err := el.ChainBundle(chain)
			if err != nil {
				return nil, err
			}
			opts = append(opts, chainParam)
		}
		return opts, nil
	}

	return &clients.ExecutionClient{
		Client: cm,
		Logger: testnet.T,
		Config: config,
		Deploy: deploy,
	}
}

// Prepares a beacon client object with all the necessary information
// to start
func (p *PreparedTestnet) prepareBeaconNode(
	parentCtx context.Context,
	testnet *Testnet,
	beaconDef *hivesim.ClientDefinition,
	config *clients.BeaconClientConfig,
	eth1Endpoints ...*clients.ExecutionClient,
) *clients.BeaconClient {
	if beaconDef == nil {
		return nil
	}

	testnet.Logf("Preparing beacon node: %s (%s)", beaconDef.Name, beaconDef.Version)

	if len(eth1Endpoints) == 0 {
		panic(fmt.Errorf("at least 1 execution endpoint is required"))
	}

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: beaconDef,
		Port:                 int64(config.BeaconAPIPort),
	}

	cl := &clients.BeaconClient{
		Client: cm,
		Logger: testnet.T,
		Config: config,
	}

	// This method will return the options used to run the client.
	// Requires a method that returns the rest of the currently running
	// beacon clients on the network at startup.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.beaconOpts}

		// Hook up beacon node to (maybe multiple) eth1 nodes
		var addrs []string
		var engineAddrs []string
		for _, en := range eth1Endpoints {
			if !en.IsRunning() || en.Proxy() == nil {
				return nil, fmt.Errorf("attempted to start beacon node when the execution client is not yet running")
			}
			execNode := en.Proxy()
			userRPC, err := execNode.UserRPCAddress()
			if err != nil {
				return nil, fmt.Errorf(
					"eth1 node used for beacon without available RPC: %v",
					err,
				)
			}
			addrs = append(addrs, userRPC)
			engineRPC, err := execNode.EngineRPCAddress()
			if err != nil {
				return nil, fmt.Errorf("eth1 node used for beacon without available RPC: %v", err)
			}
			engineAddrs = append(engineAddrs, engineRPC)
		}
		opts = append(opts, hivesim.Params{
			"HIVE_TAIKO2_ETH1_RPC_ADDRS":        strings.Join(addrs, ","),
			"HIVE_TAIKO2_ETH1_ENGINE_RPC_ADDRS": strings.Join(engineAddrs, ","),
			"HIVE_TAIKO2_BEACON_NODE_INDEX":     fmt.Sprintf("%d", config.ClientIndex),
		})

		currentlyRunningBcs := testnet.BeaconClients().
			Running().
			Subnet(config.Subnet)
		if len(currentlyRunningBcs) > 0 {
			if bootnodeENRs, err := currentlyRunningBcs.ENRs(parentCtx); err != nil {
				return nil, fmt.Errorf(
					"failed to get ENR as bootnode for every beacon node: %v",
					err,
				)
			} else if bootnodeENRs != "" {
				opts = append(opts, hivesim.Params{"HIVE_TAIKO2_BOOTNODE_ENRS": bootnodeENRs})
			}

			if staticPeers, err := currentlyRunningBcs.P2PAddrs(parentCtx); err != nil {
				return nil, fmt.Errorf("failed to get p2paddr for every beacon node: %v", err)
			} else if staticPeers != "" {
				opts = append(opts, hivesim.Params{"HIVE_TAIKO2_STATIC_PEERS": staticPeers})
			}
		}

		opts = append(
			opts,
			hivesim.Params{
				"HIVE_TERMINAL_TOTAL_DIFFICULTY": fmt.Sprintf(
					"%d",
					config.TerminalTotalDifficulty,
				),
			},
		)

		return opts, nil
	}

	return cl
}

// Prepares a validator client object with all the necessary information
// to eventually start the client.
func (p *PreparedTestnet) prepareValidatorClient(
	parentCtx context.Context,
	testnet *Testnet,
	validatorDef *hivesim.ClientDefinition,
	bn *clients.BeaconClient,
	keyIndex int,
) *clients.ValidatorClient {
	if validatorDef == nil {
		return nil
	}
	testnet.Logf(
		"Preparing validator client: %s (%s)",
		validatorDef.Name,
		validatorDef.Version,
	)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: validatorDef,
	}

	// This method will return the options used to run the client.
	// Requires the beacon client object to which to connect.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		if !bn.IsRunning() {
			return nil, fmt.Errorf("attempted to start a validator when the beacon node is not running")
		}
		// Hook up validator to beacon node
		bnAPIOpt := hivesim.Params{
			"HIVE_TAIKO2_BN_API_IP":   bn.GetHost(),
			"HIVE_TAIKO2_BN_API_PORT": fmt.Sprintf("%d", bn.Config.BeaconAPIPort),
		}
		opts := []hivesim.StartOption{p.validatorOpts, bnAPIOpt}

		return opts, nil
	}

	return &clients.ValidatorClient{
		Client:       cm,
		Logger:       testnet.T,
		ClientIndex:  keyIndex,
		BeaconClient: bn,
	}
}

func (p *PreparedTestnet) prepareTaikoGethClient(
	ctx context.Context,
	testnet *Testnet,
	eth2Def *hivesim.ClientDefinition,
) *clients.TaikoGethClient {
	if eth2Def == nil {
		return nil
	}
	testnet.Logf("Preparing TaikoGeth client: %s (%s)", eth2Def.Name, eth2Def.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: eth2Def,
		Port:                 exec_client.PortEngineRPC,
	}
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.taikoGethOpts}
		return opts, nil
	}

	return &clients.TaikoGethClient{
		Client: cm,
		Logger: testnet.T,
	}
}

func (p *PreparedTestnet) prepareDriverClient(
	ctx context.Context,
	testnet *Testnet,
	l1Client *clients.ExecutionClient,
	beaconClient *clients.BeaconClient,
	l2Client *clients.TaikoGethClient,
	driverDef *hivesim.ClientDefinition,
) *clients.DriverClient {
	if driverDef == nil || l1Client == nil || beaconClient == nil || l2Client == nil {
		return nil
	}
	testnet.Logf("Preparing driver client: %s (%s)", driverDef.Name, driverDef.Version)
	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: driverDef,
	}

	getEnvs := func() hivesim.Params {
		envs := params.EnvParams.Copy()
		envs["L1_HTTP"] = fmt.Sprintf("http://%v:8545", l1Client.GetHost())
		envs["L1_WS"] = fmt.Sprintf("ws://%v:8546", l1Client.GetHost())
		envs["L1_BEACON"] = fmt.Sprintf("http://%v:3500", beaconClient.GetHost())
		envs["L2_AUTH"] = fmt.Sprintf("http://%v:8551", l2Client.GetHost())
		envs["L2_HTTP"] = fmt.Sprintf("http://%v:8545", l2Client.GetHost())
		envs["L2_WS"] = fmt.Sprintf("ws://%v:8546", l2Client.GetHost())
		return envs
	}

	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.driverOpts, getEnvs()}
		return opts, nil
	}

	return &clients.DriverClient{
		Client: cm,
		Logger: testnet.T,
	}
}

func (p *PreparedTestnet) prepareProposerClient(
	ctx context.Context,
	testnet *Testnet,
	l1Client *clients.ExecutionClient,
	beaconClient *clients.BeaconClient,
	l2Client *clients.TaikoGethClient,
	proposerDef *hivesim.ClientDefinition,
) *clients.ProposerClient {
	if proposerDef == nil || l1Client == nil || beaconClient == nil || l2Client == nil {
		return nil
	}
	testnet.Logf("Preparing proposer client: %s (%s)", proposerDef.Name, proposerDef.Version)

	getEnvs := func() hivesim.Params {
		envs := params.EnvParams.Copy()
		envs["L1_HTTP"] = fmt.Sprintf("http://%v:8545", l1Client.GetHost())
		envs["L1_WS"] = fmt.Sprintf("ws://%v:8546", l1Client.GetHost())
		envs["L1_BEACON"] = fmt.Sprintf("http://%v:3500", beaconClient.GetHost())
		envs["L2_AUTH"] = fmt.Sprintf("http://%v:8551", l2Client.GetHost())
		envs["L2_HTTP"] = fmt.Sprintf("http://%v:8545", l2Client.GetHost())
		envs["L2_WS"] = fmt.Sprintf("ws://%v:8546", l2Client.GetHost())
		return envs
	}

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: proposerDef,
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.proposerOpts, getEnvs()}
			return opts, nil
		},
	}

	return &clients.ProposerClient{
		Client: cm,
		Logger: testnet.T,
	}
}

func (p *PreparedTestnet) prepareProverClient(
	ctx context.Context,
	testnet *Testnet,
	l1Client *clients.ExecutionClient,
	beaconClient *clients.BeaconClient,
	l2Client *clients.TaikoGethClient,
	proverDef *hivesim.ClientDefinition,
) *clients.ProverClient {
	if proverDef == nil || l1Client == nil || beaconClient == nil || l2Client == nil {
		return nil
	}
	testnet.Logf("Preparing prover client: %s (%s)", proverDef.Name, proverDef.Version)

	getEnvs := func() hivesim.Params {
		envs := params.EnvParams.Copy()
		envs["L1_HTTP"] = fmt.Sprintf("http://%v:8545", l1Client.GetHost())
		envs["L1_WS"] = fmt.Sprintf("ws://%v:8546", l1Client.GetHost())
		envs["L1_BEACON"] = fmt.Sprintf("http://%v:3500", beaconClient.GetHost())
		envs["L2_AUTH"] = fmt.Sprintf("http://%v:8551", l2Client.GetHost())
		envs["L2_HTTP"] = fmt.Sprintf("http://%v:8545", l2Client.GetHost())
		envs["L2_WS"] = fmt.Sprintf("ws://%v:8546", l2Client.GetHost())
		return envs
	}

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: proverDef,
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.proverOpts, getEnvs()}
			return opts, nil
		},
	}

	return &clients.ProverClient{
		Client: cm,
		Logger: testnet.T,
	}
}
