package testnet

import (
	"encoding/json"
	"fmt"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/hive/hivesim"
	"math/big"
	"taiko/common/clients"
	cl "taiko/common/config/consensus"
	el "taiko/common/config/execution"
	"taiko/params"
)

var (
	DEFAULT_SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY = big.NewInt(128)
	DEFAULT_MAX_CONSECUTIVE_ERRORS_ON_WAITS     = 3
)

// PreparedTestnet has all the options for starting nodes, ready to build the network.
type PreparedTestnet struct {
	// Consensus chain configuration
	Spec *cl.Spec

	// Execution chain configuration and genesis info
	ExecutionGenesis *el.ExecutionGenesis

	// L1chain configuration to apply to every node of the given type
	executionOpts hivesim.StartOption
	validatorOpts hivesim.StartOption
	beaconOpts    hivesim.StartOption
	blobOpts      hivesim.StartOption

	// L2chain configuration to apply to every node of the given type
	taikoGethOpts hivesim.StartOption
	driverOpts    hivesim.StartOption
	proposerOpts  hivesim.StartOption
	proverOpts    hivesim.StartOption
}

func getLogLevelString(logLevel int) string {
	switch logLevel {
	case 0:
		return "silent"
	case 1:
		return "error"
	case 2:
		return "warn"
	case 3:
		return "info"
	case 4:
		return "debug"
	case 5:
		return "detail"
	}
	return "info"
}

// Build all artifacts require to start a testnet.
func PrepareTestnet(
	cfg *Config,
	generateState *el.GenesisState,
) (*PreparedTestnet, error) {
	// Show cfg file
	if configJson, err := json.MarshalIndent(cfg, "", "  "); err != nil {
		panic(err)
	} else {
		fmt.Printf("Testnet config: %s\n", configJson)
	}

	executionGenesis, spec, err := el.BuildExecutionGenesis(generateState)
	if err != nil {
		return nil, fmt.Errorf("error producing execution genesis: %v", err)
	}

	genesisJsonBundle, err := el.ExecutionBundle(executionGenesis.Genesis)
	if err != nil {
		return nil, fmt.Errorf("unable to bundle execution genesis: %v", err)
	}

	// Write info so that the genesis state can be generated by the client
	genesisSSZBundle, err := cl.StateBundle(executionGenesis.GenesisState)
	if err != nil {
		return nil, fmt.Errorf("error producing state bundle: %v", err)
	}

	configBundle, err := cl.ConfigBundle(params.ConfigContent)
	if err != nil {
		return nil, fmt.Errorf("error producing consensus cfg bundle: %v", err)
	}

	// network settings
	networkParams := hivesim.WithInitialNetworks([]string{cfg.Network})

	commonParams := hivesim.Params{
		"HIVE_LOGLEVEL":          getLogLevelString(cfg.LogLevel),
		"HIVE_TAIKO_JWT_SECRET":  cfg.JWTSecret,
		"HIVE_TAIKO_FEE_RECEIPT": cfg.FeeReceipt,
	}

	executionOpts := hivesim.Bundle(
		genesisJsonBundle,
		commonParams,
		networkParams,
		// Add for anvil.
		hivesim.Params{
			"HIVE_TAIKO2_BLOCK_TIME": fmt.Sprintf("%d", spec.SecondsPerSlot),
			"HIVE_CHECK_LIVE_PORT":   fmt.Sprintf("%d", clients.EthHttpPort),
		},
	)

	beaconParams := hivesim.Params{
		"HIVE_TAIKO_DEPOSIT_CONTRACT_ADDRESS":    executionGenesis.DepositAddress,
		"HIVE_TAIKO_DEPOSIT_DEPLOY_BLOCK_NUMBER": fmt.Sprintf("%d", executionGenesis.Block.NumberU64()),
		"HIVE_TAIKO_ETH1_GENESIS_TIME":           fmt.Sprintf("%d", executionGenesis.Genesis.Timestamp),
		"HIVE_TAIKO_CHAIN_ID":                    fmt.Sprintf("%d", executionGenesis.ChainID()),
	}

	beaconOpts := hivesim.Bundle(
		configBundle,
		genesisSSZBundle,
		commonParams,
		beaconParams,
		networkParams,
		hivesim.Params{
			"HIVE_CHECK_LIVE_PORT": fmt.Sprintf("%d", clients.BeaconPort),
		},
	)

	validatorParams := hivesim.Params{
		"HIVE_TAIKO_NUM_VALIDATORS": fmt.Sprintf("%d", executionGenesis.GenesisState.NumValidators()),
	}

	validatorOpts := hivesim.Bundle(
		configBundle,
		commonParams,
		validatorParams,
		networkParams,
	)

	taikoGethOpts := hivesim.Bundle(commonParams, networkParams, hivesim.Params{
		"HIVE_NODETYPE":        cfg.L2SyncMode,
		"HIVE_LOGLEVEL":        fmt.Sprintf("%d", cfg.LogLevel),
		"HIVE_CHECK_LIVE_PORT": fmt.Sprintf("%d", clients.EthHttpPort),
	})

	taikoClientOpts := hivesim.Bundle(
		commonParams,
		networkParams,
	)

	return &PreparedTestnet{
		Spec:             spec,
		blobOpts:         networkParams,
		ExecutionGenesis: executionGenesis,
		executionOpts:    executionOpts,
		beaconOpts:       beaconOpts,
		validatorOpts:    validatorOpts,
		taikoGethOpts:    taikoGethOpts,
		driverOpts:       taikoClientOpts,
		proposerOpts:     taikoClientOpts,
		proverOpts:       taikoClientOpts,
	}, nil
}

func (p *PreparedTestnet) createTestnet(t *hivesim.T, config *Config) *Testnet {
	genesisState := p.ExecutionGenesis.GenesisState
	genesisTime := genesisState.GenesisTime()
	genesisValidatorsRoot := genesisState.GenesisValidatorsRoot()
	return &Testnet{
		T:                     t,
		genesisTime:           genesisTime,
		genesisValidatorsRoot: common.BytesToHash(genesisValidatorsRoot),
		spec:                  p.Spec,
		executionGenesis:      p.ExecutionGenesis,

		Debug: config.Debug,
	}
}

func (p *PreparedTestnet) prepareAnvilNode(
	testnet *Testnet,
	cfg *Config,
	anvilDef *hivesim.ClientDefinition,
) {
	if anvilDef == nil {
		return
	}
	testnet.Logf("Preparing anvil node: %s (%s)", anvilDef.Name, anvilDef.Version)
	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: anvilDef,
		Network:              cfg.Network,
	}
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.executionOpts}

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp:%d", clients.AnvilPort, clients.AnvilPort),
			})
		}

		return opts, nil
	}

	testnet.Nodes[0].AnvilClient = &clients.AnvilClient{
		SecondsPerSlot: testnet.spec.SecondsPerSlot,
		EthNode: &clients.EthNode{
			HiveManagedClient: cm,
			HttpPort:          clients.AnvilPort,
			WSPort:            clients.AnvilPort,
		},
	}
}

// Prepares an execution client object with all the necessary information
// to start
func (p *PreparedTestnet) prepareExecutionNode(
	index int,
	testnet *Testnet,
	cfg *Config,
	eth1Def *hivesim.ClientDefinition,
	consensus el.ExecutionConsensus,
) {
	if eth1Def == nil {
		return
	}
	testnet.Logf("Preparing execution node: %s (%s)", eth1Def.Name, eth1Def.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: eth1Def,
		Network:              cfg.Network,
	}

	// This method will return the options used to run the client.
	// Requires a method that returns the rest of the currently running
	// execution clients on the network at startup.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.executionOpts}
		opts = append(opts, consensus.HiveParams(index))

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp,%d/tcp", clients.EthHttpPort, clients.EthWSPort),
			})
		}

		return opts, nil
	}

	testnet.Nodes[0].L1EthClient = &clients.ExecutionClient{
		EthNode: &clients.EthNode{
			HiveManagedClient: cm,
		},
	}
}

// Prepares a beacon client object with all the necessary information
// to start
func (p *PreparedTestnet) prepareBeaconNode(
	testnet *Testnet,
	cfg *Config,
	beaconDef *hivesim.ClientDefinition,
) {
	if beaconDef == nil {
		return
	}

	testnet.Logf("Preparing beacon node: %s (%s)", beaconDef.Name, beaconDef.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		Network:              cfg.Network,
		HiveClientDefinition: beaconDef,
	}

	// This method will return the options used to run the client.
	// Requires a method that returns the rest of the currently running
	// beacon clients on the network at startup.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.beaconOpts}

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp", clients.BeaconPort),
			})
		}

		opts = append(opts, hivesim.Params{
			"HIVE_TAIKO_ETH1_RPC_ADDRS": testnet.Nodes[0].L1EthClient.EngineURL(),
		})

		return opts, nil
	}

	testnet.Nodes[0].BeaconClient = &clients.BeaconClient{
		HiveManagedClient: cm,
	}
}

// Prepares a validator client object with all the necessary information
// to eventually start the client.
func (p *PreparedTestnet) prepareValidatorClient(
	testnet *Testnet,
	validatorDef *hivesim.ClientDefinition,
) {

	var (
		firstNode = testnet.Nodes[0]
		bn        = firstNode.BeaconClient
	)

	if validatorDef == nil {
		return
	}

	testnet.Logf(
		"Preparing validator client: %s (%s)",
		validatorDef.Name,
		validatorDef.Version,
	)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: validatorDef,
	}

	// This method will return the options used to run the client.
	// Requires the beacon client object to which to connect.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		if !bn.IsRunning() {
			return nil, fmt.Errorf("attempted to start a validator when the beacon node is not running")
		}
		// Hook up validator to beacon node
		bnAPIOpt := hivesim.Params{
			"HIVE_TAIKO_BN_API_IP": bn.GetHost(),
		}
		opts := []hivesim.StartOption{p.validatorOpts, bnAPIOpt}

		return opts, nil
	}

	firstNode.ValidatorClient = &clients.ValidatorClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareTaikoGethClient(
	index int,
	testnet *Testnet,
	cfg *Config,
	eth2Def *hivesim.ClientDefinition,
) {
	if eth2Def == nil {
		testnet.Logf("No eth2 client definition provided")
		return
	}
	testnet.Logf("Preparing TaikoGeth client: %s (%s)", eth2Def.Name, eth2Def.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: eth2Def,
		Network:              cfg.Network,
	}
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.taikoGethOpts}

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp,%d/tcp,%d/tcp", clients.EthHttpPort, clients.EthWSPort, clients.EthEngineRPC),
			})
		}

		bootnode, err := testnet.L2EthClients().Running().Enodes()
		if err != nil {
			return nil, err
		}
		opts = append(opts, hivesim.Params{"HIVE_BOOTNODE": bootnode})

		return opts, nil
	}

	testnet.Nodes[index].L2EthClient = &clients.TaikoGethClient{
		EthNode: &clients.EthNode{
			HiveManagedClient: cm,
		},
	}
}

func (p *PreparedTestnet) prepareDriverClient(
	index int,
	testnet *Testnet,
	cfg *Config,
	driverDef *hivesim.ClientDefinition,
) {
	if driverDef == nil {
		return
	}
	var (
		firstNode = testnet.Nodes[0]
		node      = testnet.Nodes[index]
	)
	testnet.Logf("Preparing driver client: %s (%s)", driverDef.Name, driverDef.Version)
	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: driverDef,
	}

	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.driverOpts, getTaikoClientEnvs(firstNode, node)}
		if index > 0 && cfg.BeaconSync {
			opts = append(opts, hivesim.Params{
				"P2P_SYNC":                 "true",
				"P2P_CHECK_POINT_SYNC_URL": firstNode.L2EthClient.HttpURL(),
			})
		}

		return opts, nil
	}

	node.DriverClient = &clients.DriverClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareProposerClient(
	index int,
	testnet *Testnet,
	proposerDef *hivesim.ClientDefinition,
) {
	var (
		firstNode = testnet.Nodes[0]
		node      = testnet.Nodes[index]
	)

	if proposerDef == nil {
		return
	}
	testnet.Logf("Preparing proposer client: %s (%s)", proposerDef.Name, proposerDef.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: proposerDef,
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.proposerOpts, getTaikoClientEnvs(firstNode, node)}
			return opts, nil
		},
	}

	node.ProposerClient = &clients.ProposerClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareProverClient(
	index int,
	testnet *Testnet,
	proverDef *hivesim.ClientDefinition,
) {
	var (
		firstNode = testnet.Nodes[0]
		node      = testnet.Nodes[index]
	)
	if proverDef == nil {
		return
	}
	testnet.Logf("Preparing prover client: %s (%s)", proverDef.Name, proverDef.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: proverDef,
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.proverOpts, getTaikoClientEnvs(firstNode, node)}
			return opts, nil
		},
	}

	node.ProverClient = &clients.ProverClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareBlobScanClient(
	index int,
	testnet *Testnet,
	config *Config,
	clientsByRole map[clients.Role]*hivesim.ClientDefinition,
) {
	if clientsByRole[clients.BlobApi] == nil || params.ParamByKey("TEST_BLOB_SERVER") != "true" {
		return
	}

	firstNode := testnet.Nodes[0]

	redis := &clients.HiveManagedClient{
		T:                    testnet.T,
		Network:              config.Network,
		HiveClientDefinition: clientsByRole[clients.Redis],
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.blobOpts}
			// Expose the eth1 ports to the host.
			if testnet.Debug {
				opts = append(opts, hivesim.Params{
					"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("6379/tcp"),
				})
			}
			return opts, nil
		},
	}
	mysql := &clients.HiveManagedClient{
		T:                    testnet.T,
		Network:              config.Network,
		HiveClientDefinition: clientsByRole[clients.Postgres],
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.blobOpts}

			// Expose the eth1 ports to the host.
			if testnet.Debug {
				opts = append(opts, hivesim.Params{
					"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("5432/tcp"),
				})
			}

			return opts, nil
		},
	}
	blobApi := &clients.HiveManagedClient{
		T:                    testnet.T,
		Network:              config.Network,
		HiveClientDefinition: clientsByRole[clients.BlobApi],
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.blobOpts}
			opts = append(opts, hivesim.Params{
				"CHAIN_ID":                 fmt.Sprintf("%d", testnet.executionGenesis.ChainID()),
				"DATABASE_URL":             firstNode.BlobScanClient.PostgresURL(),
				"REDIS_URI":                firstNode.BlobScanClient.RedisURL(),
				"SECRET_KEY":               "supersecret",
				"POSTGRES_STORAGE_ENABLED": "true",
				"NETWORK_NAME":             "devnet",
			})

			// Expose the eth1 ports to the host.
			if testnet.Debug {
				opts = append(opts, hivesim.Params{
					"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("3001/tcp"),
				})
			}

			return opts, nil
		},
	}
	blobIndexer := &clients.HiveManagedClient{
		T:                    testnet.T,
		Network:              config.Network,
		HiveClientDefinition: clientsByRole[clients.BlobIndexer],
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.blobOpts}
			opts = append(opts, hivesim.Params{
				"SECRET_KEY":              "supersecret",
				"BLOBSCAN_API_ENDPOINT":   firstNode.BlobScanClient.BlobAPIURL(),
				"BEACON_NODE_ENDPOINT":    firstNode.BeaconClient.BeaconURL(),
				"EXECUTION_NODE_ENDPOINT": firstNode.L1EthClient.HttpURL(),
				"NETWORK_NAME":            "devnet",
			})
			return opts, nil
		},
	}

	testnet.Nodes[index].BlobScanClient = &clients.BlobScanClient{
		Redis:       redis,
		Mysql:       mysql,
		BlobApi:     blobApi,
		BlobIndexer: blobIndexer,
	}
}

func getTaikoClientEnvs(
	firstNode, node *clients.Node,
) hivesim.Params {
	var (
		anvilClient  = firstNode.AnvilClient
		l1Client     = firstNode.L1EthClient
		beaconClient = firstNode.BeaconClient
		blobClient   = firstNode.BlobScanClient
		l2Client     = node.L2EthClient
	)

	envs := params.EnvParams()
	envs["L2_AUTH"] = l2Client.EngineURL()
	envs["L2_HTTP"] = l2Client.HttpURL()
	envs["L2_WS"] = l2Client.WSURL()
	if anvilClient != nil {
		envs["L1_HTTP"] = anvilClient.HttpURL()
		envs["L1_WS"] = anvilClient.WSURL()
		envs["L1_BEACON"] = anvilClient.HttpURL()
	}
	if l1Client != nil {
		envs["L1_HTTP"] = l1Client.HttpURL()
		envs["L1_WS"] = l1Client.WSURL()
		envs["L1_BEACON"] = beaconClient.BeaconURL()
	}

	// This variables are set for blob tests.
	if envs["TEST_L1_BEACON"] == "true" {
		delete(envs, "RUN_TESTS")
	} else if envs["TEST_BLOB_SERVER"] == "true" {
		delete(envs, "L1_BEACON")
		envs["BLOB_SERVER"] = blobClient.BlobAPIURL()
	}

	return envs
}
