package testnet

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/ethereum/hive/hivesim"
	exec_client "github.com/marioevz/eth-clients/clients/execution"
	"github.com/protolambda/zrnt/eth2/beacon/common"
	"math/big"
	"strings"
	"taiko/common/clients"
	cl "taiko/common/config/consensus"
	consensus_config "taiko/common/config/consensus"
	el "taiko/common/config/execution"
	"taiko/params"
)

var (
	DEFAULT_SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY = big.NewInt(128)
	DEFAULT_MAX_CONSECUTIVE_ERRORS_ON_WAITS     = 3
)

// PreparedTestnet has all the options for starting nodes, ready to build the network.
type PreparedTestnet struct {
	// Consensus chain configuration
	Spec *consensus_config.Spec

	// Execution chain configuration and genesis info
	ExecutionGenesis *el.ExecutionGenesis

	// L1chain configuration to apply to every node of the given type
	executionOpts hivesim.StartOption
	validatorOpts hivesim.StartOption
	beaconOpts    hivesim.StartOption

	// L2chain configuration to apply to every node of the given type
	taikoGethOpts hivesim.StartOption
	driverOpts    hivesim.StartOption
	proposerOpts  hivesim.StartOption
	proverOpts    hivesim.StartOption
}

func getLogLevelString(logLevel int) string {
	switch logLevel {
	case 0:
		return "silent"
	case 1:
		return "error"
	case 2:
		return "warn"
	case 3:
		return "info"
	case 4:
		return "debug"
	case 5:
		return "detail"
	}
	return "info"
}

// Build all artifacts require to start a testnet.
func PrepareTestnet(
	cfg *Config,
	generateState *el.GenesisState,
) (*PreparedTestnet, error) {
	// Show cfg file
	if configJson, err := json.MarshalIndent(cfg, "", "  "); err != nil {
		panic(err)
	} else {
		fmt.Printf("Testnet config: %s\n", configJson)
	}

	executionGenesis, spec, err := el.BuildExecutionGenesis(generateState)
	if err != nil {
		return nil, fmt.Errorf("error producing execution genesis: %v", err)
	}

	genesisJsonBundle, err := el.ExecutionBundle(executionGenesis.Genesis)
	if err != nil {
		return nil, fmt.Errorf("unable to bundle execution genesis: %v", err)
	}

	// Write info so that the genesis state can be generated by the client
	genesisSSZBundle, err := cl.StateBundle(executionGenesis.GenesisState)
	if err != nil {
		return nil, fmt.Errorf("error producing state bundle: %v", err)
	}

	configBundle, err := cl.ConfigBundle(params.ConfigContent)
	if err != nil {
		return nil, fmt.Errorf("error producing consensus cfg bundle: %v", err)
	}

	// network settings
	networkParams := hivesim.WithInitialNetworks([]string{cfg.Network})

	commonParams := hivesim.Params{
		"HIVE_LOGLEVEL":          getLogLevelString(cfg.LogLevel),
		"HIVE_TAIKO_JWT_SECRET":  cfg.JWTSecret,
		"HIVE_TAIKO_FEE_RECEIPT": cfg.FeeReceipt,
	}

	executionOpts := hivesim.Bundle(
		genesisJsonBundle,
		commonParams,
		networkParams,
		// Add for anvil.
		hivesim.Params{
			"HIVE_TAIKO2_BLOCK_TIME": fmt.Sprintf("%d", spec.SecondsPerSlot),
			"HIVE_CHECK_LIVE_PORT":   fmt.Sprintf("%d", clients.EthHttpPort),
		},
	)

	beaconParams := hivesim.Params{
		"HIVE_TAIKO_DEPOSIT_CONTRACT_ADDRESS":    executionGenesis.DepositAddress,
		"HIVE_TAIKO_DEPOSIT_DEPLOY_BLOCK_NUMBER": fmt.Sprintf("%d", executionGenesis.Block.NumberU64()),
		"HIVE_TAIKO_ETH1_GENESIS_TIME":           fmt.Sprintf("%d", executionGenesis.Genesis.Timestamp),
		"HIVE_TAIKO_CHAIN_ID":                    fmt.Sprintf("%d", executionGenesis.ChainID()),
	}

	beaconOpts := hivesim.Bundle(
		configBundle,
		genesisSSZBundle,
		commonParams,
		beaconParams,
		networkParams,
		hivesim.Params{
			"HIVE_CHECK_LIVE_PORT": fmt.Sprintf("%d", clients.BeaconPort),
		},
	)

	validatorParams := hivesim.Params{
		"HIVE_TAIKO_NUM_VALIDATORS": fmt.Sprintf("%d", executionGenesis.GenesisState.NumValidators()),
	}

	validatorOpts := hivesim.Bundle(
		configBundle,
		commonParams,
		validatorParams,
		networkParams,
	)

	taikoGethOpts := hivesim.Bundle(commonParams, networkParams, hivesim.Params{
		"HIVE_NODETYPE":        cfg.L2SyncMode,
		"HIVE_LOGLEVEL":        fmt.Sprintf("%d", cfg.LogLevel),
		"HIVE_CHECK_LIVE_PORT": fmt.Sprintf("%d", clients.EthHttpPort),
	})

	params.SetEnvParams("IS_GUARDIAN", fmt.Sprintf("%v", cfg.IsGuardian))
	if !cfg.IsGuardian {
		params.SetEnvParams("GUARDIAN_PROVER_MINORITY", "")
		params.SetEnvParams("GUARDIAN_PROVER_MAJORITY", "")
		params.SetEnvParams("GUARDIAN_PROVER_CONTRACT", "")
	}
	taikoClientOpts := hivesim.Bundle(
		params.EnvParams(),
		commonParams,
		networkParams,
		hivesim.Params{
			"TX_RECEIPT_QUERY_INTERVAL": "1s",
		},
	)

	return &PreparedTestnet{
		Spec:             spec,
		ExecutionGenesis: executionGenesis,
		executionOpts:    executionOpts,
		beaconOpts:       beaconOpts,
		validatorOpts:    validatorOpts,
		taikoGethOpts:    taikoGethOpts,
		driverOpts:       taikoClientOpts,
		proposerOpts:     taikoClientOpts,
		proverOpts:       taikoClientOpts,
	}, nil
}

func (p *PreparedTestnet) createTestnet(t *hivesim.T, config *Config) *Testnet {
	genesisState := p.ExecutionGenesis.GenesisState
	genesisTime := genesisState.GenesisTime()
	genesisValidatorsRoot := genesisState.GenesisValidatorsRoot()
	return &Testnet{
		T:                     t,
		genesisTime:           common.Timestamp(genesisTime),
		genesisValidatorsRoot: common.Root(genesisValidatorsRoot),
		spec:                  p.Spec,
		executionGenesis:      p.ExecutionGenesis,

		Debug: config.Debug,
	}
}

func (p *PreparedTestnet) prepareAnvilNode(
	network string,
	testnet *Testnet,
	anvilDef *hivesim.ClientDefinition,
) *clients.AnvilClient {
	if anvilDef == nil {
		return nil
	}
	testnet.Logf("Preparing anvil node: %s (%s)", anvilDef.Name, anvilDef.Version)
	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: anvilDef,
		Network:              network,
		Port:                 clients.AnvilPort,
	}
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.executionOpts}

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp:%d", clients.AnvilPort, clients.AnvilPort),
			})
		}

		return opts, nil
	}

	return &clients.AnvilClient{
		SecondsPerSlot: testnet.spec.SecondsPerSlot,
		EthNode: &clients.EthNode{
			HiveManagedClient: cm,
			HttpPort:          clients.AnvilPort,
			WSPort:            clients.AnvilPort,
		},
	}
}

// Prepares an execution client object with all the necessary information
// to start
func (p *PreparedTestnet) prepareExecutionNode(
	testnet *Testnet,
	eth1Def *hivesim.ClientDefinition,
	consensus el.ExecutionConsensus,
	config clients.ExecutionClientConfig,
) *clients.ExecutionClient {
	if eth1Def == nil {
		return nil
	}
	testnet.Logf("Preparing execution node: %s (%s)", eth1Def.Name, eth1Def.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: eth1Def,
		Network:              config.Network,
		Port:                 clients.EthEngineRPC,
	}

	// This method will return the options used to run the client.
	// Requires a method that returns the rest of the currently running
	// execution clients on the network at startup.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.executionOpts}
		opts = append(opts, consensus.HiveParams(config.ClientIndex))

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp,%d/tcp", clients.EthHttpPort, clients.EthWSPort),
			})
		}

		return opts, nil
	}

	return &clients.ExecutionClient{
		EthNode: &clients.EthNode{
			HiveManagedClient: cm,
		},
		Config: config,
	}
}

// Prepares a beacon client object with all the necessary information
// to start
func (p *PreparedTestnet) prepareBeaconNode(
	ctx context.Context,
	testnet *Testnet,
	beaconDef *hivesim.ClientDefinition,
	config *clients.BeaconClientConfig,
	eth1Endpoints ...*clients.ExecutionClient,
) *clients.BeaconClient {
	if beaconDef == nil {
		return nil
	}

	testnet.Logf("Preparing beacon node: %s (%s)", beaconDef.Name, beaconDef.Version)

	if len(eth1Endpoints) == 0 {
		panic(fmt.Errorf("at least 1 execution endpoint is required"))
	}

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: beaconDef,
		Port:                 int64(clients.BeaconPort),
	}

	cl := &clients.BeaconClient{
		HiveManagedClient: cm,
		Config:            config,
	}

	// This method will return the options used to run the client.
	// Requires a method that returns the rest of the currently running
	// beacon clients on the network at startup.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.beaconOpts}

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp", clients.BeaconPort),
			})
		}

		// Hook up beacon node to (maybe multiple) eth1 nodes
		var engineAddrs []string
		for _, en := range eth1Endpoints {
			if !en.IsRunning() {
				return nil, fmt.Errorf("attempted to start beacon node when the execution client is not yet running")
			}
			engineAddrs = append(engineAddrs, en.EngineURL())
		}
		opts = append(opts, hivesim.Params{
			"HIVE_TAIKO_ETH1_RPC_ADDRS": strings.Join(engineAddrs, ","),
		})

		return opts, nil
	}

	return cl
}

// Prepares a validator client object with all the necessary information
// to eventually start the client.
func (p *PreparedTestnet) prepareValidatorClient(
	testnet *Testnet,
	validatorDef *hivesim.ClientDefinition,
	bn *clients.BeaconClient,
) *clients.ValidatorClient {
	if validatorDef == nil {
		return nil
	}
	testnet.Logf(
		"Preparing validator client: %s (%s)",
		validatorDef.Name,
		validatorDef.Version,
	)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: validatorDef,
	}

	// This method will return the options used to run the client.
	// Requires the beacon client object to which to connect.
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		if !bn.IsRunning() {
			return nil, fmt.Errorf("attempted to start a validator when the beacon node is not running")
		}
		// Hook up validator to beacon node
		bnAPIOpt := hivesim.Params{
			"HIVE_TAIKO_BN_API_IP": bn.GetHost(),
		}
		opts := []hivesim.StartOption{p.validatorOpts, bnAPIOpt}

		return opts, nil
	}

	return &clients.ValidatorClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareTaikoGethClient(
	network string,
	testnet *Testnet,
	eth2Def *hivesim.ClientDefinition,
) *clients.TaikoGethClient {
	if eth2Def == nil {
		testnet.Logf("No eth2 client definition provided")
		return nil
	}
	testnet.Logf("Preparing TaikoGeth client: %s (%s)", eth2Def.Name, eth2Def.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: eth2Def,
		Network:              network,
		Port:                 exec_client.PortEngineRPC,
	}
	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		opts := []hivesim.StartOption{p.taikoGethOpts}

		// Expose the eth1 ports to the host.
		if testnet.Debug {
			opts = append(opts, hivesim.Params{
				"HIVE_DOCKER_PORT_BINDINGS": fmt.Sprintf("%d/tcp,%d/tcp,%d/tcp", clients.EthHttpPort, clients.EthWSPort, clients.EthEngineRPC),
			})
		}

		bootnode, err := testnet.L2EthClients().Running().Enodes()
		if err != nil {
			return nil, err
		}
		opts = append(opts, hivesim.Params{"HIVE_BOOTNODE": bootnode})

		return opts, nil
	}

	return &clients.TaikoGethClient{
		EthNode: &clients.EthNode{
			HiveManagedClient: cm,
		},
	}
}

func (p *PreparedTestnet) prepareDriverClient(
	index int,
	testnet *Testnet,
	driverDef *hivesim.ClientDefinition,
	cfg *clients.TaikoClientConfig,
	firstNode *clients.Node,
	l2Client *clients.TaikoGethClient,
) *clients.DriverClient {
	var (
		anvilClient  = firstNode.AnvilClient
		l1Client     = firstNode.L1EthClient
		beaconClient = firstNode.BeaconClient
	)
	if driverDef == nil ||
		(l1Client == nil && anvilClient == nil || l1Client != nil && anvilClient != nil) ||
		l2Client == nil {
		return nil
	}
	if l1Client != nil && beaconClient == nil || l1Client == nil && beaconClient != nil {
		testnet.Fatalf("driver failed to prepare, l1Client and beaconClient must be both nil or both not nil")
	}
	testnet.Logf("Preparing driver client: %s (%s)", driverDef.Name, driverDef.Version)
	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: driverDef,
	}

	cm.OptionsGenerator = func() ([]hivesim.StartOption, error) {
		envs := getAPIEnvs(anvilClient, l1Client, beaconClient, l2Client)
		opts := []hivesim.StartOption{p.driverOpts, envs}
		if index > 0 && cfg.BeaconSync {
			opts = append(opts, hivesim.Params{
				"P2P_SYNC":                 "true",
				"P2P_CHECK_POINT_SYNC_URL": firstNode.L2EthClient.HttpURL(),
			})
		}
		return opts, nil
	}

	return &clients.DriverClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareProposerClient(
	testnet *Testnet,
	proposerDef *hivesim.ClientDefinition,
	anvilClient *clients.AnvilClient,
	l1Client *clients.ExecutionClient,
	beaconClient *clients.BeaconClient,
	l2Client *clients.TaikoGethClient,
) *clients.ProposerClient {
	if proposerDef == nil ||
		(l1Client == nil && anvilClient == nil || l1Client != nil && anvilClient != nil) ||
		l2Client == nil {
		return nil
	}
	if l1Client != nil && beaconClient == nil || l1Client == nil && beaconClient != nil {
		testnet.Fatalf("proposer failed to prepare, l1Client and beaconClient must be both nil or both not nil")
	}
	testnet.Logf("Preparing proposer client: %s (%s)", proposerDef.Name, proposerDef.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: proposerDef,
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.proposerOpts, getAPIEnvs(anvilClient, l1Client, beaconClient, l2Client)}
			opts = append(opts, hivesim.Params{
				"EPOCH_INTERVAL": "1s",
			})
			return opts, nil
		},
	}

	return &clients.ProposerClient{
		HiveManagedClient: cm,
	}
}

func (p *PreparedTestnet) prepareProverClient(
	testnet *Testnet,
	proverDef *hivesim.ClientDefinition,
	anvilClient *clients.AnvilClient,
	l1Client *clients.ExecutionClient,
	beaconClient *clients.BeaconClient,
	l2Client *clients.TaikoGethClient,
) *clients.ProverClient {
	if proverDef == nil ||
		(l1Client == nil && anvilClient == nil || l1Client != nil && anvilClient != nil) ||
		l2Client == nil {
		return nil
	}
	if l1Client != nil && beaconClient == nil || l1Client == nil && beaconClient != nil {
		testnet.Fatalf("prover failed to prepare, l1Client and beaconClient must be both nil or both not nil")
	}
	testnet.Logf("Preparing prover client: %s (%s)", proverDef.Name, proverDef.Version)

	cm := &clients.HiveManagedClient{
		T:                    testnet.T,
		HiveClientDefinition: proverDef,
		OptionsGenerator: func() ([]hivesim.StartOption, error) {
			opts := []hivesim.StartOption{p.proverOpts, getAPIEnvs(anvilClient, l1Client, beaconClient, l2Client)}
			return opts, nil
		},
	}

	return &clients.ProverClient{
		HiveManagedClient: cm,
	}
}

func getAPIEnvs(
	anvilClient *clients.AnvilClient,
	l1Client *clients.ExecutionClient,
	beaconClient *clients.BeaconClient,
	l2Client *clients.TaikoGethClient,
) hivesim.Params {
	envs := hivesim.Params{}
	envs["L2_AUTH"] = l2Client.EngineURL()
	envs["L2_HTTP"] = l2Client.HttpURL()
	envs["L2_WS"] = l2Client.WSURL()
	if anvilClient != nil {
		envs["L1_HTTP"] = anvilClient.HttpURL()
		envs["L1_WS"] = anvilClient.WSURL()
		envs["L1_BEACON"] = anvilClient.HttpURL()
		envs["RUN_TESTS"] = "true"
	}
	if l1Client != nil {
		envs["L1_HTTP"] = l1Client.HttpURL()
		envs["L1_WS"] = l1Client.WSURL()
		envs["L1_BEACON"] = beaconClient.BeaconURL()
	}

	return envs
}
