CONFIG_NAME: interop
PRESET_BASE: interop

MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 128
MIN_GENESIS_TIME: 1606824000
GENESIS_FORK_VERSION: 0x0000000a
GENESIS_DELAY: 604800
ALTAIR_FORK_VERSION: 0x0100000a
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x0200000a
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x0300000a
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x0400000a
DENEB_FORK_EPOCH: 0
TERMINAL_BLOCK_HASH: 0x8166d71e94885f12070e8cec5ec37cd03bfbec94ea5997c3c8e0cecd5022c37c
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0
SECONDS_PER_SLOT: 6
SECONDS_PER_ETH1_BLOCK: 14
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 0
SHARD_COMMITTEE_PERIOD: 0
ETH1_FOLLOW_DISTANCE: 1
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 2
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8
PROPOSER_SCORE_BOOST: 40
DEPOSIT_CHAIN_ID: 7
DEPOSIT_NETWORK_ID: 7
DEPOSIT_CONTRACT_ADDRESS: 0x4e59b44847b379578588920ca78fbf26c0b4956c
GOSSIP_MAX_SIZE: 10485760
MAX_REQUEST_BLOCKS: 1024
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
MAX_CHUNK_SIZE: 10485760
TTFB_TIMEOUT: 5
RESP_TIMEOUT: 10
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
SUBNETS_PER_NODE: 2
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6
MAX_REQUEST_BLOCKS_DENEB: 128
MAX_REQUEST_BLOB_SIDECARS: 768
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
BLOB_SIDECAR_SUBNET_COUNT: 6
TERMINAL_TOTAL_DIFFICULTY: 0